/**
 * Capture the book: which venues hold a market in the issuer's stock tokens,
 * asked of the venues themselves.
 *
 * The discovery itself lives in `lib/chain/pool-discovery.ts` and is the same
 * code the Registrar runs once a day to diff this file against the chain. Two
 * implementations of "what pools exist" would drift from each other, and the
 * drift report would then be measuring the difference between two guesses.
 *
 * The output is a generated module, like the feed directory and the stock-token
 * registry before it: committed, carrying the block it was read at, and re-run
 * rather than edited. A pool created after the capture is not in the book until
 * the capture runs again — a stated boundary, which the Registrar now reports
 * as a condition rather than leaving for somebody to notice.
 *
 * Run: node scripts/capture-stock-pools.ts [--write] [--check]
 */

import { writeFileSync } from 'node:fs';
import { activeNetwork, rpcUrl } from '../lib/chain/networks.ts';
import { readHead, readChainId } from '../lib/chain/rpc.ts';
import { isRead } from '../lib/doctrine/reading.ts';
import { discoverStockPools, PRICED_STOCK_TOKENS, QUOTE_ASSETS } from '../lib/chain/pool-discovery.ts';
import { diffPools } from '../lib/chain/capture-drift.ts';
import { V3_FEE_TIERS, V4_TIERS, V4_HOOKS } from '../lib/chain/venues.ts';

const OUTPUT = 'lib/chain/stock-pools.ts';

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  const write = args.has('--write');
  const check = args.has('--check');
  const network = activeNetwork();
  const opts = { intervalSeconds: 900, timeoutMs: 90_000 };

  const [chainId, head] = await Promise.all([readChainId(opts), readHead(opts)]);
  if (!isRead(chainId) || !isRead(head)) {
    console.error('the chain could not be reached; nothing is captured rather than guessed');
    process.exit(1);
  }
  if (chainId.value !== network.chainId) {
    console.error(`the node answered chain ${chainId.value}; ${network.label} is ${network.chainId}`);
    process.exit(1);
  }

  const retrievedAt = new Date(head.value.timestamp * 1000).toISOString();
  console.log(`# ${network.label} (${network.chainId}) via ${rpcUrl(network)}`);
  console.log(`# head ${head.value.number.toLocaleString('en-US')} at ${retrievedAt}`);
  console.log(`# asking the factories about ${PRICED_STOCK_TOKENS.length} priced stock tokens against ${QUOTE_ASSETS.length} quote assets\n`);

  const found = await discoverStockPools(opts);
  const records = found.pools;
  const tickers = new Set(records.map((r) => r.ticker));
  const byVenue = { v2: 0, v3: 0, v4: 0 };
  for (const r of records) byVenue[r.venue] += 1;

  console.log(`## ${records.length} pools across ${tickers.size} of ${found.tickersProbed} priced tokens`);
  console.log(`   v2 ${byVenue.v2} · v3 ${byVenue.v3} · v4 ${byVenue.v4} · ${found.probesUnread} of ${found.probesMade} probes unread`);
  const without = PRICED_STOCK_TOKENS.filter((t) => !tickers.has(t.ticker)).map((t) => t.ticker);
  if (without.length > 0) console.log(`   priced by the directory but holding no pool this capture can name: ${without.join(', ')}`);

  if (check) {
    const drift = diffPools(records);
    console.log(`\n## against the committed book: ${drift.added.length} added, ${drift.removed.length} no longer discoverable`);
    if (drift.added.length > 0) console.log(`   added: ${drift.added.slice(0, 20).map((p) => p.key).join(', ')}${drift.added.length > 20 ? ' …' : ''}`);
    if (drift.removed.length > 0) console.log(`   gone:  ${drift.removed.slice(0, 20).map((p) => p.key).join(', ')}${drift.removed.length > 20 ? ' …' : ''}`);
    if (drift.tickersGained.length > 0) console.log(`   tickers that gained their first pool: ${drift.tickersGained.join(', ')}`);
    if (!write && (drift.added.length > 0 || drift.removed.length > 0)) process.exitCode = 1;
  }

  const lines = records.map((r) => `  ${JSON.stringify(r)},`);
  const header = [
    '/**',
    ' * Every venue holding a market in a priced stock token, as the factories',
    ' * answered on the date below. GENERATED by scripts/capture-stock-pools.ts —',
    ' * do not edit by hand; re-run the capture and commit the diff.',
    ' *',
    ' * A v2 or v3 pool is named by its own address. A v4 pool has no address: it is',
    ' * named by `poolId`, recomputed from the key recorded here, and its state is',
    ' * read from the StateView lens. `address` for a v4 row is the PoolManager,',
    ' * because that is what a reader would point at and what every event comes from.',
    ' *',
    ' * `tokenIsCurrency0` is decided by address order, which is how both the v3',
    ' * factory and the v4 key sort their pair. It decides which side of the mid the',
    ' * stock token is on, and getting it backwards would invert every price here.',
    ' *',
    ' * The Registrar runs the same discovery once a day and reports what this file',
    ' * no longer matches (`capture:pools:DRIFT`), so a stale book is a condition',
    ' * rather than something somebody has to think to check.',
    ' */',
    '',
    'export interface StockPoolRecord {',
    '  readonly key: string;',
    '  readonly ticker: string;',
    '  readonly token: string;',
    '  readonly tokenDecimals: number;',
    '  /** The Chainlink feed that prices the underlying. The reference half of a basis. */',
    '  readonly feedKey: string;',
    "  readonly venue: 'v2' | 'v3' | 'v4';",
    '  /** The pool for v2 and v3; the PoolManager for v4. */',
    '  readonly address: string;',
    '  readonly poolId: string | null;',
    '  readonly fee: number | null;',
    '  readonly tickSpacing: number | null;',
    '  readonly hooks: string | null;',
    '  readonly quoteKey: string;',
    '  readonly quoteLabel: string;',
    '  readonly quoteAddress: string;',
    '  readonly quoteDecimals: number;',
    '  /** The feed that turns the quote asset into US dollars. */',
    '  readonly quoteFeedKey: string;',
    '  readonly tokenIsCurrency0: boolean;',
    '  readonly decimals0: number;',
    '  readonly decimals1: number;',
    '}',
    '',
    'export const STOCK_POOLS_SOURCE = {',
    `  network: ${JSON.stringify(network.label)},`,
    `  chainId: ${network.chainId},`,
    `  observedAt: ${JSON.stringify(retrievedAt)},`,
    `  observedAtBlock: ${head.value.number},`,
    `  tokensProbed: ${found.tickersProbed},`,
    `  tokensWithAPool: ${tickers.size},`,
    `  pools: ${records.length},`,
    `  byVenue: { v2: ${byVenue.v2}, v3: ${byVenue.v3}, v4: ${byVenue.v4} },`,
    `  probesUnread: ${found.probesUnread},`,
    '  /** Asked about, and therefore findable. Anything outside these was never asked. */',
    `  feeTiersAsked: ${JSON.stringify(V3_FEE_TIERS)},`,
    `  v4TiersAsked: ${JSON.stringify(V4_TIERS)},`,
    `  hooksAsked: ${JSON.stringify(V4_HOOKS)},`,
    '} as const;',
    '',
    'export const STOCK_POOLS: readonly StockPoolRecord[] = [',
  ].join('\n');

  const module = `${header}\n${lines.join('\n')}\n];\n`;
  if (write) {
    writeFileSync(OUTPUT, module);
    console.log(`\nwrote ${OUTPUT} (${records.length} pools)`);
  } else {
    console.log(`\ndry run — ${OUTPUT} not written. Pass --write to write it.`);
  }
}

await main();
